name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared package
        run: pnpm build:shared

      - name: Typecheck (shared)
        run: pnpm --filter @qubic-messenger/shared typecheck

      - name: Typecheck (web)
        run: pnpm --filter web typecheck

      - name: Lint
        run: pnpm lint

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: lint-typecheck
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared
        run: pnpm build:shared

      - name: Build web
        run: pnpm build:web
        env:
          NEXT_PUBLIC_RELAY_ADDR: ${{ vars.RELAY_ADDR }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: frontend/web/.next
          retention-days: 7

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared
        run: pnpm build:shared

      - name: Run tests
        run: pnpm test
